# Generated by Django 6.0.3 on 2026-03-09 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criteria',
            old_name='percentage_weight',
            new_name='percentage',
        ),
    ]
